# Generated by Django 5.0.6 on 2024-07-10 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cauthor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='titel',
            new_name='title',
        ),
    ]
